#这是一个基本的工作流程，可以帮助您开始行动

名字: 居里

#控制工作流何时运行
在:
  #触发push或pull请求事件的工作流，但只针对“main”分支
推:
分支: [ "main" ]
query为空pull_request:
分支: [ "main" ]

  #允许您从Actions选项卡手动运行此工作流
  workflow_dispatch:

#工作流运行由一个或多个作业组成，这些作业可以按顺序或并行运行
工作:
  #这个工作流包含一个名为“build”的作业
建筑:
    #作业将在其上运行的运行程序类型
    runs-on: ubuntu-latest

    #Steps表示将作为作业的一部分执行的一系列任务
步骤:
      #Checks-在$GITHUB_WORKSPACE下取出存储库，这样您的作业就可以访问它了
      - 用途: actions/checkout@v4

      #使用runner shell运行单个命令
      - 名字: 运行单行脚本
跑: 你好，世界！

      #使用runner shell运行一组命令
      - 名字: 运行多行脚本
跑: |
添加其他动作来构建，
回显测试，并部署项目。
